In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [2]:
df = pd.DataFrame({
'x': [12, 20, 28, 18, 29, 33, 24, 45, 45, 52, 51, 52, 55, 53, 55, 61, 64,
69, 72],
'y': [39, 36, 30, 52, 54, 46, 55, 59, 63, 70, 66, 63, 58, 23, 14, 8, 19,
7, 24]
})

In [15]:
len(df.to_numpy())

19

In [16]:
def Kmeans(df, K, iter = 10):
    df = df.to_numpy()
    row = len(df)
    centroids = df[np.random.randint(row, size = K),:]
    for i in range(iter): 
        distance = np.zeros((row,K), dtype = int)
        for j in range(K):
            distance[:,j] = np.array([math.sqrt(np.sum((centroids[j]-x)**2)) for x in df])
        cluster = np.array([d.argmin() for d in distance])
        for new in range(K):
            df_new = df[cluster == new,:]
            centroids[new,:] = np.sum(df_new,axis = 0) / df_new.shape[0]
    return cluster, centroids

In [28]:
Kmeans(df, 2, iter = 10)

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       dtype=int64),
 array([[62, 15],
        [35, 53]], dtype=int64))

In [29]:
Kmeans(df, 3, iter = 10)

(array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2],
       dtype=int64),
 array([[50, 63],
        [23, 44],
        [62, 15]], dtype=int64))

In [24]:
Kmeans(df, 4, iter = 10)

(array([3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 1],
       dtype=int64),
 array([[50, 63],
        [63, 22],
        [61,  9],
        [23, 44]], dtype=int64))